version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      -  pip install pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/globalnetwork"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/device"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/site"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/link"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/transitgatewayregistration"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/linkassociation"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/customergatewayassociation"
      - mvn clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/globalnetwork/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/device/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/site/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/link/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/transitgatewayregistration/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/linkassociation/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/customergatewayassociation/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/corenetwork/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/connectattachment/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/connectpeer/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/sitetositevpnattachment/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/vpcattachment/rpdk.log"
